# Generated by Django 5.2.8 on 2025-11-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, default='reviews/Avis.jpg', null=True, upload_to='reviews/'),
        ),
    ]
