# Generated by Django 5.2.8 on 2025-11-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='people',
            field=models.IntegerField(default=1),
        ),
    ]
