# Generated by Django 5.2.8 on 2025-11-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_first_name_reservation_name_and_more'),
    ]

    operations = [
    ]
